name: "smtp-sink"
on:
  push:
    paths:
    - "smtp-sink/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking out"
      uses: actions/checkout@v1

    - name: "Building docker image"
      working-directory: smtp-sink/
      run: docker build -t camptocamp/smtp-sink .

    - name: "Pushing image to docker hub"
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker push camptocamp/smtp-sink
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}